# Generated by Django 5.2 on 2026-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('ready', 'Préparée'), ('delivered', 'Livrée'), ('canceled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
