# Generated by Django 5.2 on 2026-06-17 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_heroimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroimage',
            options={'ordering': ['-is_active', '-created_at']},
        ),
        migrations.AddField(
            model_name='heroimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
